In [5]:
import numpy as np
from numpy import *

In [9]:
#31. How to ignore all numpy warnings (not recommended)? (★☆☆)

with np.errstate(divide='ignore'):
    a=np.ones(1)/0

In [10]:
#32. Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)


C:\Users\roshan\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [12]:
np.emath.sqrt(-1)

1j

In [13]:
np.sqrt(-1)

C:\Users\roshan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [18]:
#33. How to get the dates of yesterday, today and tomorrow?
today=datetime64('today','D')+timedelta64(0,'D')
print(today)

2019-08-05


In [24]:
#34. How to get all the dates corresponding to the month of July 2016?
arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [30]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?          ################### ***
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
C

array([3., 3., 3.])

In [42]:
#36. Extract the integer part of a random array using 5 different methods 
from numpy.random import *
seed(5)
a= np.random.uniform(0,10,10)
print(a)
np.floor(a)
np.ceil(a)-1
a.astype(int)




[2.21993171 8.70732306 2.06719155 9.18610908 4.88411189 6.11743863
 7.65907856 5.18417988 2.96800502 1.87721229]


array([2, 8, 2, 9, 4, 6, 7, 5, 2, 1])

In [59]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4 
a=np.zeros((5,5))
a+=np.arange(5)
a


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [64]:
#38. Consider a generator function that generates 10 integers and use it to build an array
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=int,count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [67]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
np.arange(0.0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [72]:
#40. Create a random vector of size 10 and sort it
b=np.random.random(10)
b.sort()
b

array([0.00164217, 0.02293309, 0.02430656, 0.20455555, 0.51547261,
       0.57766286, 0.63979518, 0.69984361, 0.77951459, 0.9856244 ])

In [78]:
#41. How to sum a small array faster than np.sum?
a=np.arange(50)
add.reduce(a)
np.sum(a)

1225

In [81]:
#42. Consider two random array A and B, check if they are equal
a=np.random.random(10)
b=np.random.random(10)
(a==b)

array([False, False, False, False, False, False, False, False, False,
       False])

In [83]:
#43. Make an array immutable (read-only)
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] 

0.0

In [87]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates  ############***
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.99817134 1.24022351 0.38283231 0.32631603 0.888152   0.45374091
 0.85502528 0.25027147 0.81224465 0.25912277]
[0.77937939 0.9037042  0.21868622 0.74604143 1.14901188 1.43796001
 0.31418513 1.31467652 1.46586887 0.85393102]


In [103]:
#45. Create random vector of size 10 and replace the maximum value by 0
a=np.random.random_sample(10)
a[a.argmax()]=0
a

array([0.14038611, 0.07544315, 0.68808941, 0.82006319, 0.61670132,
       0.        , 0.63052799, 0.80032326, 0.36206458, 0.02771319])

In [104]:
#46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [105]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [106]:
#48. Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [114]:
#49. How to print all the values of an array?
np.set_printoptions(threshold=0)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [117]:
#50. How to find the closest value (to a given scalar) in a vector?
a=np.random.rand(10)
b=a.round()
print(a)
b

[0.57121237 0.97955853 0.75972725 ... 0.0196347  0.24587483 0.03076044]


array([1., 1., 1., ..., 0., 0., 0.])

In [2]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b) 
import numpy as np
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [3]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances 
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.38770672 0.52769293 0.56658942 0.70902495 0.31433583
  0.47898517 0.94033701 0.12964691 0.38174024]
 [0.38770672 0.         0.58132202 0.34652872 0.33089611 0.48332753
  0.28559715 0.55279552 0.36553189 0.66966488]
 [0.52769293 0.58132202 0.         0.91845199 0.71222312 0.22308562
  0.84360111 0.98187647 0.39919898 0.36535104]
 [0.56658942 0.34652872 0.91845199 0.         0.51108968 0.78435752
  0.08765167 0.58241853 0.61795955 0.93143154]
 [0.70902495 0.33089611 0.71222312 0.51108968 0.         0.71175821
  0.50390031 0.27105804 0.65793777 0.92425068]
 [0.31433583 0.48332753 0.22308562 0.78435752 0.71175821 0.
  0.70143716 0.97908986 0.19286744 0.21698805]
 [0.47898517 0.28559715 0.84360111 0.08765167 0.50390031 0.70143716
  0.         0.61532648 0.53180007 0.84452871]
 [0.94033701 0.55279552 0.98187647 0.58241853 0.27105804 0.97908986
  0.61532648 0.         0.90825637 1.18881918]
 [0.12964691 0.36553189 0.39919898 0.61795955 0.65793777 0.19286744
  0.53180007 0.90825

In [5]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
a=2.365
b=int(a)
b

2

In [6]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
#54. How to read the following file? (★★☆)
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
    
    


SyntaxError: invalid syntax (<ipython-input-8-89b2e699070a>, line 3)

In [9]:
from io import StringIO

# Fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [10]:
#55. What is the equivalent of enumerate for numpy arrays? (★★☆)
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [11]:
#56. Generate a generic 2D Gaussian-like array (★★☆
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [12]:
#57. How to randomly place p elements in a 2D array?

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
#58. Subtract the mean of each row of a matrix
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.0325573  -0.28887704 -0.26442372 -0.05297237 -0.20601211 -0.21230488
   0.02403829  0.37218841  0.38140677  0.21439934]
 [ 0.18674529  0.1228159   0.16827669 -0.30431966  0.23998157 -0.11986662
  -0.49565806 -0.18229148  0.09529943  0.28901694]
 [ 0.17442817 -0.47137001  0.29957025  0.17545279 -0.15316047  0.31210207
  -0.58186408  0.28777642 -0.34225953  0.2993244 ]
 [ 0.10321791 -0.33831831  0.44889939 -0.08038488  0.30807425  0.14081249
  -0.32985537 -0.34645091  0.1386151  -0.04460965]
 [-0.36484679  0.11005302 -0.21723819  0.39620111 -0.13394484  0.51120422
  -0.03853066 -0.1233617   0.07318799 -0.21272415]]


In [14]:
#59. How to sort an array by the nth column? 
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[4 9 3]
 [6 2 4]
 [7 2 6]]
[[6 2 4]
 [7 2 6]
 [4 9 3]]


In [24]:
#60. How to tell if a given 2D array has null columns?
a=np.arange(0,10).reshape(2,5)
a==np.nan


array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [21]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [27]:
#61. Find the nearest value from a given value in an array
Z = np.random.uniform(0,1,10)
z = 0.9
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.8802244473166527


In [28]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [29]:
#63. Create an array class that has a name attribute 
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [30]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[2. 2. 4. 1. 3. 3. 7. 2. 4. 2.]
[ 3.  3.  7.  1.  5.  5. 13.  3.  7.  3.]


In [31]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [32]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [33]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once?
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[59 65 51 65]
 [55 61 53 61]
 [57 50 59 57]]
[[59 65 51 65]
 [55 61 53 61]
 [57 50 59 57]]


In [34]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? 
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.51524206 0.49660862 0.60463767 0.61921812 0.54910504 0.59086179
 0.39696396 0.60496221 0.57445354 0.65662373]
0    0.515242
1    0.496609
2    0.604638
3    0.619218
4    0.549105
5    0.590862
6    0.396964
7    0.604962
8    0.574454
9    0.656624
dtype: float64


In [38]:
#69. How to get the diagonal of a dot product?
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

c=np.dot(A,B)
print(np.diag(c))

[0.55133794 0.87804847 1.3026328  0.74681928 1.18656685]


In [39]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [40]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [41]:
#72. How to swap two rows of an array?
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [42]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique 
#line segments composing all the triangles 
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1,  3) ( 1, 66) ( 3, 66) ( 6, 14) ( 6, 15) ( 8, 19) ( 8, 24) (14, 15)
 (19, 24) (24, 41) (24, 64) (28, 41) (28, 61) (35, 40) (35, 91) (36, 61)
 (36, 71) (40, 91) (41, 48) (41, 61) (41, 64) (41, 81) (48, 81) (54, 62)
 (54, 81) (61, 71) (62, 81) (73, 74) (73, 95) (74, 95)]


In [43]:
#74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [44]:
#75. How to compute averages using a sliding window over an array?
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [45]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [46]:
#77. How to negate a boolean, or to change the sign of a float inplace?
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-8.01013741e-01, -2.70301853e-01, -7.51849884e-01, -9.56459427e-01,
        8.36009128e-01, -6.50231140e-02, -6.85466525e-01,  1.63320620e-02,
       -2.45568498e-01,  5.54485173e-02, -3.20152962e-01, -2.36702121e-02,
        8.61887529e-01,  8.04904079e-01,  1.04507579e-01,  3.90565702e-01,
        3.83868685e-01, -7.21308516e-02, -9.87193086e-01,  3.07709308e-01,
       -9.56371488e-01,  1.05874436e-02, -9.51023819e-01,  5.11546750e-02,
       -7.03686004e-01,  5.83706321e-01,  6.60072823e-01, -8.01622253e-01,
        6.17788649e-01,  2.52183897e-01,  4.59812708e-01,  4.20266875e-01,
       -6.51232146e-01, -5.28429261e-01, -3.23221832e-01, -1.74903347e-01,
       -7.43079006e-01, -4.12384507e-01, -4.81813312e-01,  4.03789291e-01,
       -6.68209845e-01, -8.24252738e-01,  2.04588809e-01, -7.32031152e-01,
        8.51816495e-01, -6.69420727e-01,  4.75364736e-01, -3.80867590e-01,
        6.94216865e-01,  6.40800974e-01, -8.53333545e-01, -4.35688210e-01,
        9.71996203e-01,  

In [47]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[14.47753045  2.81798718  0.26201435 14.24946207  4.0037167   3.84680557
  5.71355421 10.82032854  3.18486893  1.5614711 ]


In [48]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[9.17093645e+00 5.35079088e+00 4.76013172e+00 1.39091403e+01
  4.74674928e+00 3.29907598e+00 5.14178765e+00 6.19400595e+00
  2.62866956e+00 8.86501342e+00]
 [8.46900228e+00 3.73306835e+00 8.79994693e+00 1.32960643e+01
  1.82562738e+01 5.65880942e+00 4.95033843e+00 6.18204335e+00
  1.61833412e+01 1.25650784e+01]
 [8.31259874e+00 4.65680710e+00 2.80841898e+00 1.30629022e+01
  6.71766542e+00 2.62882209e+00 3.22885953e+00 4.15772586e+00
  4.58290010e+00 8.64565278e+00]
 [1.04098653e+01 2.01004740e+00 4.17070406e+00 1.52081420e+01
  1.35848049e+01 3.99137070e+00 4.70848496e-01 1.38420860e+00
  1.15485399e+01 1.29910366e+01]
 [6.29357663e-01 1.83961887e+01 1.33664374e+01 5.30297865e+00
  3.51323217e+00 1.63309576e+01 6.08388896e+00 1.10228806e+01
  5.93508974e+00 2.40641461e+00]
 [9.78304088e+00 5.25947430e+00 5.32841860e+00 1.45180516e+01
  4.16020707e+00 3.19817247e+00 5.91894698e+00 6.90886241e+00
  2.05807324e+00 9.28848511e+00]
 [3.53981642e-01 1.80377485e+01 1.17438554e+01 4.32945278e

In [49]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 2 2 2 4 9 1 1 2 1]
 [4 8 9 3 1 3 1 0 7 3]
 [0 7 7 6 9 9 0 1 5 6]
 [6 4 7 6 6 6 8 0 9 2]
 [8 2 9 5 3 7 2 8 6 5]
 [2 0 7 6 0 1 0 6 5 0]
 [8 8 5 3 8 1 3 3 0 9]
 [3 2 1 8 1 1 3 5 0 8]
 [3 1 2 6 7 1 0 5 5 9]
 [3 6 6 5 1 6 7 3 6 3]]
[[0 0 0 0 0]
 [0 8 2 2 2]
 [0 4 8 9 3]
 [0 0 7 7 6]
 [0 6 4 7 6]]


C:\Users\roshan\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [50]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [53]:
#82. Compute a matrix rank
Z = np.random.uniform(0,1,(5,5))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

5


In [52]:
Z

array([[0.00691103, 0.37784148, 0.2546791 , 0.39016411, 0.1957595 ,
        0.37366701, 0.70181843, 0.48045631, 0.89343115, 0.70572777],
       [0.66709709, 0.8227517 , 0.26860141, 0.1639794 , 0.53622915,
        0.077139  , 0.71140796, 0.4594469 , 0.43612737, 0.33532329],
       [0.61312449, 0.44142794, 0.48652645, 0.52622614, 0.27363074,
        0.2907076 , 0.10083885, 0.27642856, 0.23734654, 0.23301916],
       [0.08732885, 0.89874748, 0.05917279, 0.25828625, 0.07062363,
        0.71099387, 0.8231026 , 0.54954189, 0.31249658, 0.54819844],
       [0.59879062, 0.45324292, 0.49970548, 0.06235017, 0.70623404,
        0.13548918, 0.81317847, 0.12979578, 0.18022055, 0.42590181],
       [0.25334781, 0.50418477, 0.48327386, 0.87257443, 0.07369929,
        0.93282905, 0.51815746, 0.9690465 , 0.65772827, 0.25439464],
       [0.36308161, 0.30141738, 0.42070365, 0.96293909, 0.81212194,
        0.74033941, 0.73434363, 0.66139385, 0.62196218, 0.09182028],
       [0.55782621, 0.34173064, 0.6869563

In [54]:
#83. How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

0


In [55]:
Z

array([9, 0, 4, 6, 0, 0, 3, 1, 7, 3, 0, 9, 7, 1, 7, 8, 0, 4, 1, 9, 0, 1,
       3, 7, 1, 4, 3, 1, 4, 3, 5, 3, 5, 1, 0, 0, 3, 3, 1, 2, 2, 6, 2, 0,
       9, 7, 0, 8, 8, 6])

In [56]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 0 0]
   [0 1 2]
   [3 2 3]]

  [[0 0 0]
   [1 2 1]
   [2 3 3]]

  [[0 0 2]
   [2 1 3]
   [3 3 2]]

  [[0 2 1]
   [1 3 0]
   [3 2 2]]

  [[2 1 2]
   [3 0 3]
   [2 2 4]]

  [[1 2 1]
   [0 3 1]
   [2 4 1]]

  [[2 1 1]
   [3 1 0]
   [4 1 3]]

  [[1 1 3]
   [1 0 4]
   [1 3 1]]]


 [[[0 1 2]
   [3 2 3]
   [3 4 2]]

  [[1 2 1]
   [2 3 3]
   [4 2 1]]

  [[2 1 3]
   [3 3 2]
   [2 1 3]]

  [[1 3 0]
   [3 2 2]
   [1 3 3]]

  [[3 0 3]
   [2 2 4]
   [3 3 0]]

  [[0 3 1]
   [2 4 1]
   [3 0 0]]

  [[3 1 0]
   [4 1 3]
   [0 0 1]]

  [[1 0 4]
   [1 3 1]
   [0 1 2]]]


 [[[3 2 3]
   [3 4 2]
   [4 4 1]]

  [[2 3 3]
   [4 2 1]
   [4 1 3]]

  [[3 3 2]
   [2 1 3]
   [1 3 2]]

  [[3 2 2]
   [1 3 3]
   [3 2 4]]

  [[2 2 4]
   [3 3 0]
   [2 4 4]]

  [[2 4 1]
   [3 0 0]
   [4 4 3]]

  [[4 1 3]
   [0 0 1]
   [4 3 2]]

  [[1 3 1]
   [0 1 2]
   [3 2 4]]]


 [[[3 4 2]
   [4 4 1]
   [2 4 4]]

  [[4 2 1]
   [4 1 3]
   [4 4 0]]

  [[2 1 3]
   [1 3 2]
   [4 0 3]]

  [[1 3 3]
   [3 2 4]
   [0 3 4]]

  [[3 3 0]
   

In [57]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i] 
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7 11 12  9 10]
 [11  7  3 15  8]
 [12  3  8 42 12]
 [ 9 15 42  3 16]
 [10  8 12 16  4]]


In [58]:
#86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [59]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [60]:
#88. How to implement the Game of Life using numpy arrays? (★★★)
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [61]:
##### 89. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9998 9999 9997 9995]


In [62]:
#90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [63]:
#91. How to create a record array from a regular array? (★★★)
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [64]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.44 s ± 107 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
798 ms ± 67.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
554 ms ± 77.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [65]:
#93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 3 5]


In [66]:
#94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 1 3]
 [1 4 0]
 [2 4 3]
 [1 1 4]
 [1 1 4]
 [1 4 3]
 [4 4 1]
 [2 0 2]
 [0 4 2]
 [2 4 0]]
[[3 1 3]
 [1 4 0]
 [2 4 3]
 [1 1 4]
 [1 1 4]
 [1 4 3]
 [4 4 1]
 [2 0 2]
 [0 4 2]
 [2 4 0]]
[[3 1 3]
 [1 4 0]
 [2 4 3]
 [1 1 4]
 [1 1 4]
 [1 4 3]
 [4 4 1]
 [2 0 2]
 [0 4 2]
 [2 4 0]]


In [67]:
#95. Convert a vector of ints into a matrix binary representation (★★★)
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [68]:
#96. Given a two dimensional array, how to extract unique rows? (★★★)
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]]
[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]]


In [69]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.10833658, 0.1405052 , 0.0553406 , 0.0590784 , 0.13492671,
        0.06030876, 0.01050739, 0.09367489, 0.02809002, 0.03896578],
       [0.47672789, 0.61828377, 0.24352262, 0.25997058, 0.59373601,
        0.26538466, 0.04623708, 0.41221013, 0.12360825, 0.17146632],
       [0.27386089, 0.35517902, 0.1398939 , 0.14934258, 0.34107732,
        0.15245276, 0.02656133, 0.23679805, 0.07100794, 0.09850047],
       [0.62775525, 0.81415602, 0.32067057, 0.34232924, 0.78183153,
        0.34945851, 0.06088498, 0.54279827, 0.16276734, 0.22578684],
       [0.44677533, 0.57943733, 0.22822223, 0.24363677, 0.55643189,
        0.24871069, 0.04333203, 0.38631119, 0.11584201, 0.16069318],
       [0.32566048, 0.42235958, 0.16635422, 0.17759008, 0.40559061,
        0.18128853, 0.03158529, 0.28158737, 0.08443878, 0.1171314 ],
       [0.39544658, 0.51286742, 0.20200242, 0.21564603, 0.49250501,
        0.22013702, 0.03835373, 0.341929  , 0.10253325, 0.1422316 ],
       [0.62746401, 0.8137783 , 0.3205218

In [72]:
#98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [71]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [73]:
#100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.28261295  0.07921151]
