In [ ]:
21. Create a checkerboard 8x8 matrix using the tile function
22. Normalize a 5x5 random matrix
23. Create a custom dtype that describes color as four unsigned bytes (RGBA)   ######################## doubt
24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
25. Given a 1D array, negate all elements which are between 3 and 8, in place.
26. What is the output of the following script?
# Author: Jake VanderPlas
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
27. Consider an integer vector Z, which of these expressions are legal?
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
29. How to round away from zero a float array?###############doubt
30. How to find common values between the two arrays?

In [ ]:
#21. Create a checkerboard 8x8 matrix using the tile function
arr=np.array([[0,1],[1,0]])
np.tile(arr,(4,4))

In [ ]:
#22. Normalize a 5x5 random matrix
arr=np.random.randn(25).reshape(5,5)
arr2=(arr-arr.mean())/np.std(arr)
print(arr)
arr2

In [102]:
#23. Create a custom dtype that describes color as four unsigned bytes (RGBA)


In [13]:
import numpy as np
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
mat1=np.arange(15).reshape(5,3)
mat2=np.arange(6).reshape(3,2)
res=mat1@mat2
print(mat1,"\n\n",mat2,"\n\n",res)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

 [[0 1]
 [2 3]
 [4 5]] 

 [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [19]:
##25. Given a 1D array, negate all elements which are between 3 and 8, in place.
arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
arr[(arr>3)&(arr<8)]*=(-1)
arr


array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11])

In [ ]:
27. Consider an integer vector Z, which of these expressions are legal?
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [21]:
z=np.array([1,2,3,4])
z**z

array([  1,   4,  27, 256], dtype=int32)

In [23]:
z

array([1, 2, 3, 4])

In [25]:
2<<z>>2


array([1, 2, 4, 8], dtype=int32)

In [28]:
z<-z

array([False, False, False, False])

In [29]:
1j*z

array([0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [32]:
z

array([1, 2, 3, 4])

In [35]:
z/1/1

array([1., 2., 3., 4.])

In [44]:
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [46]:
np.array(0)/np.array(0)

C:\Users\roshan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [50]:
np.array(0)//np.array(0)

C:\Users\roshan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [52]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [96]:
#29. How to round away from zero a float array?



In [101]:
#30. How to find common values between the two arrays?
arr1=np.array([[1,2,3,4,5],[1,6,7,8,9]])
arr2=np.array([[4,5,6,2,13],[1,5,7,6,5]])
np.intersect1d(arr1,arr2)

array([1, 2, 4, 5, 6, 7])