In [76]:
import scipy
from scipy import stats

import seaborn as sb
import numpy as np
from numpy import random
from numpy.random import randn
import matplotlib.pyplot as plt
from random import seed



In [ ]:
#11. Create a 3x3 identity matrix
#12. Create a 3x3x3 array with random values
#13. Create a 10x10 array with random values and find the minimum and maximum values
#14. Create a random vector of size 30 and find the mean value
#15. Create a 2d array with 1 on the border and 0 inside
#16. How to add a border (filled with 0's) around an existing array?
#17. What is the result of the following expression?
#0 * np.nan
#np.nan == np.nan
#np.inf > np.nan
#np.nan - np.nan
#np.nan in set([np.nan])
#0.3 == 3 * 0.1

In [12]:
mat=np.matrix([[1,0,0],[0,1,0],[0,0,1]])  #11. Create a 3x3 identity matrix
np.shape(mat)

(3, 3)

In [20]:
np.random.rand(27).reshape(3,3,3)       #12. Create a 3x3x3 array with random values

array([[[0.35348582, 0.20596261, 0.26986155],
        [0.81242169, 0.98459352, 0.69119181],
        [0.21918764, 0.97448721, 0.3320361 ]],

       [[0.66007038, 0.34418957, 0.78353841],
        [0.11886977, 0.50709703, 0.69972334],
        [0.14341067, 0.77364984, 0.43867613]],

       [[0.92657234, 0.39147736, 0.30300209],
        [0.15153435, 0.16697819, 0.67123619],
        [0.63370504, 0.376159  , 0.36601369]]])

In [45]:
#seed()   #13. Create a 10x10 array with random values and find the minimum and maximum values
arr=randn(100).reshape(10,10)
print("maximum=%.2f "%arr.max(),"minimum= %.2f"%arr.min())  
arr

maximum=2.71  minimum= -3.01


array([[-1.02913579,  1.33421951,  1.09102019,  0.41575673, -1.00818767,
        -0.15572711, -0.30546083, -0.25725007, -0.46716701, -1.71598021],
       [ 0.61613858, -0.09222924, -0.50019976, -0.83823315, -1.25472078,
        -1.49234826,  0.72564181,  0.9121133 , -0.4729149 ,  0.90113516],
       [-1.0779228 ,  1.2269    ,  1.01207661,  0.74660095, -0.21083083,
        -2.08354407, -0.3988353 ,  0.94535619,  0.88227942, -0.43217055],
       [-0.06013033,  0.88976384, -0.23399001, -0.73585892,  0.544086  ,
         0.33273701,  1.28963145, -0.06745175, -2.53409227,  1.41255669],
       [-0.23762199, -0.6578369 , -0.49285373,  0.44328199,  0.52527495,
        -0.15891594, -1.02177457, -0.63133035, -0.46486745,  0.96966813],
       [-1.11101939,  0.07948375,  0.93501331, -1.09019767, -0.10075498,
        -0.32129192, -3.01308049,  0.35193098,  1.07247581,  1.26670095],
       [ 1.01456151,  1.69558671, -1.38362598,  0.91224033,  2.48173404,
         1.34963442, -1.38704334, -0.60228292

In [78]:
random.seed()  #14. Create a random vector of size 30 and find the mean value
vec=np.array(randn(30))
print("mean =%f"%vec.mean())
vec

mean =0.033012


array([ 0.85894712,  0.20873482,  0.731781  , -1.42478496,  0.5105492 ,
       -0.49479025,  1.89996853,  0.02541276,  0.32375152, -0.40358818,
       -0.47449795,  0.26626964,  1.51491675, -0.33242732, -0.07451055,
       -0.44384972, -0.50440516, -0.78156868,  0.00967706, -0.32312361,
        0.57688898, -1.20170277, -1.11422101,  1.38034501,  1.06562065,
       -0.63826542,  0.51914534, -0.54866705, -0.72927274,  0.58802564])

In [81]:
#15. Create a 2d array with 1 on the border and 0 inside
arr2=np.array([[1,1,1,1,1],[1,0,0,0,1],[1,1,1,1,1]])
arr2

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [105]:
#another way of the above question
a=np.zeros([4,4],dtype=int)
np.pad(a,pad_width=1,mode='constant',constant_values=1)

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

In [88]:
#16. How to add a border (filled with 0's) around an existing array?
np.pad(arr2,pad_width=1,mode='constant',constant_values='0')

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [109]:
np.nan==np.nan

False

In [110]:
0.3==3*0.1

False

In [1]:
import numpy as np
0*5
0*np.nan



nan

In [2]:
np.inf>np.nan

False

In [3]:
np.nan-np.nan

nan

In [4]:
np.nan in set([np.nan])

True

In [5]:
0.3==3*0.1

False

In [10]:
import pandas as pd #18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
a=np.array([[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5]])
b=pd.DataFrame(a)
print(b)
b.iloc[1,0]=1
b.iloc[2,1]=2
b.iloc[3,2]=3
b.iloc[4,3]=4
b

   0  1  2  3  4
0  5  5  5  5  5
1  5  5  5  5  5
2  5  5  5  5  5
3  5  5  5  5  5
4  5  5  5  5  5


0  1  2  3  4
0  5  5  5  5  5
1  1  5  5  5  5
2  5  2  5  5  5
3  5  5  3  5  5
4  5  5  5  4  5

In [24]:
#another way
b=np.diag(1+np.arange(4),k=-1)
b

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [65]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
a=np.zeros([8,8],dtype=int)
a[1::2,1::2]=1
a[::2,::2]=1

a


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [42]:
# another type
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [93]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
arr=np.arange(336).reshape(6,7,8)
print(np.unravel_index(99,(6,7,8)))
np.where(arr==99)   # another way using where() method

(1, 5, 3)


(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))